name: Lint
on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    paths-ignore:
      - "**.md"
  schedule:
    - cron: "0 0 * * *"

jobs:
  shellcheck:
    name: shellcheck
    runs-on: ubuntu-latest
    container:
      image: node:25-trixie
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install shellcheck
        run: apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -qqy --option Dpkg::Options::="--force-confdef" --option Dpkg::Options::="--force-confold" install shellcheck

      - name: Run shellcheck
        run: shellcheck -x -P lib bin/*

  shfmt:
    name: shfmt
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install shfmt
        run: brew install shfmt

      - name: Run shfmt
        run: shfmt -d -i 2 -ci .
